### ISSUE TITLE
WSGI affecting local Login access

### ISSUE THREAD

**Issue by pwarmuz** [pwarmuzStvns/SSW695_Capstone#4]
start.wsgi is affecting local Login access. *edit* ***it seems to be a flask issue***

>RuntimeError
>RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.

**Comment by pwarmuz** [comment]
-# set the secret key.
-flask_app.secret_key = flask_app.config.get('secret_key')
This was removed because flask_app.config.from_object(config.BaseConfig) inherits SECRET_KEY since it's reserved. 'secret_key' should be SECRET_KEY
http://flask.pocoo.org/docs/0.12/config/

**Comment by enptfb55** [comment]
did this work?

**Comment by pwarmuz** [comment]
Yes It worked for me. I did 2 updates to the 'feature/secret_fixed', the second updated uses the updated DEBUG config because I moved the DEBUG = False parameter to into config_private

**Comment by enptfb55** [comment]
ok lets merge this to develop and i can try to get it to work with wsgi

**Comment by pwarmuz** [comment]
Merged
